# Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/payment_engine
spring.datasource.username=postgres
spring.datasource.password=manav
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=your_secret_key
jwt.expiration=3600000

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173